spring:
  redis:
    host: 127.0.0.1
    port: 6379
      #lettuce:
      #pool:
      #max-wait: 100000 #连接池最大阻塞等待时间（使用负值表示没有限制）
      #max-idle: 10 #连接池中的最大空闲连接
      #max-active: 100 #连接池最大连接数（使用负值表示没有限制）
    #timeout: 5000 #连接超时时间（毫秒）
server:
  port: 9999